development:
  adapter: mysql2
  host: 'localhost'
  encoding: utf8
  database: app_development
  pool: 5
  username: tsk
  password: password

test:
  adapter: mysql2
  host: 'localhost'
  encoding: utf8
  database: app_test
  pool: 5
  username: tsk
  password: password

production:
  adapter: mysql2
  host: 'localhost'
  encoding: utf8
  database: app_production
  pool: 5
  username: tsk
  password: password
